version: '3.7'

services:
  postgres:
    image: postgres:9.6.10-alpine
    container_name: msc-messages-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages
    ports:
      - "5445:5432"
