version: '3.7'

services:
  postgres:
    image: postgres:9.6.10-alpine
    container_name: msc-updates-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: updates
    ports:
      - "5444:5432"
