version: '3.7'

services:
  postgres:
    image: postgres:9.6.10-alpine
    container_name: msc-users-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5442:5432"
