version: '3.7'

services:
  postgres:
    image: postgres:9.6.10-alpine
    container_name: msc-contacts-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contacts
    ports:
      - "5443:5432"
